/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
     repositories {
         mavenCentral()
         gradlePluginPortal()
     }
 }

rootProject.name = "commerce-demo"
include("app")